'use strict';

// Cached jQuery objects for use by various modules.
var Elements = {
  $a: $('a'),
  $body: $('body'),
  $clear: $('#clear'),
  $countsFind: $('#counts.find'),
  $cutoff: $('#cutoff'),
  $effectLinks: $('.effects a:not(#help_panel)'),
  $effects: $('.effect'),
  $findEffect: $('.effect[data-effect="find"]'),
  $findText: $('#find_text'),
  $imgsWithoutAlts: $('img:not([alt])'),
  $listEffect: $('.effect[data-effect="list"]'),
  $listStart: $('#list_start'),
  $normalEffect: $('.effect[data-effect="normal"]'),
  $numberList: $('#number_list'),
  $numberListLabel: $('#number_list_label'),
  $outputToInput: $('#outputToInput'),
  $panelHeading: $('.panel-heading'),
  $regexpToggle: $('#regexp_toggle'),
  $regexpToggleLabel: $('#regexp_toggle_label'),
  $removeListEffect: $('.effect[data-effect="remove_list"]'),
  $repeatEffect: $('.effect[data-effect="repeat"]'),
  $repetitions: $('#repetitions'),
  $replaceEffect: $('.effect#replace'),
  $replaceText: $('#replace_text'),
  $textAfter: $('#text_after'),
  $textBefore: $('#text_before'),
  $titlebar: $('.titlebar'),
  $toolbarCollapseButton: $('#toolbar_collapse_button'),
  $toolbarExpandButton: $('#toolbar_expand_button'),
  $toolbarTitlebarToggle: $('#toolbar_titlebar_toggle')
};
